apiVersion : apps/v1
kind: Deployment
metadata:
  name: vikranthimage1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikranthimage1
  template:
    metadata:
      labels:
        app: vikranthimage1 
    spec:
      containers:
        - name: vikranthimage1 
          image: aksdevopsacr18.azurecr.io/vikranthimage1
          ports:
          - containerPort: 80