apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1nginxaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1nginxaks
  template:
    metadata:
      labels:
        app: app1nginxaks 
    spec:
      containers:
        - name: vikranthapp123 
          image: aksdevopsacrv.azurecr.io/vikranthapp123
          ports:
          - containerPort: 80
